baseURL = '/blog'
languageCode = 'en-us'
title = 'wnccys'
theme = "hugo-toigian"

# themesDir = "../.."
# (Optional) If you provide a Disqus shortname, comments will be enabled on
# all pages.

[params]
# (Optional, default true): Controls table of contents visibility on right side of pages.
# Start and end levels can be controlled with markup.tableOfContents setting.
toc = true

# (Optional, default true) Enables comments template on pages
# By default partials/docs/comments.html includes Disqus template
# See https://gohugo.io/content-management/comments/#configure-disqus
# Can be overwritten by same param in page frontmatter
comments = true

[params.author]
name = "Vinicius de Souza"
email = "wnccys@proton.me"

[markup]
    defaultMarkdownHandler = "goldmark"
    # By default, Goldmark trims unsafe outputs which might prevent some shortcodes from rendering.
    # It is recommended to set markup.goldmark.renderer.unsafe=true if you encounter problems.
    [markup.goldmark]
        [markup.goldmark.renderer]
        unsafe = false  # Enable user to embed HTML snippets in Markdown content.
    [markup.highlight]
        codeFences = true
        guessSyntax = true
        lineNos = false
        noClasses = false
        tabWidth = 4
    [markup.tableOfContents]
        startLevel = 2
        endLevel = 4
        ordered = false

# The left side navbar at the top
[menu]
    [[menu.nav]]
        name = "About"
        url = "/about"
        weight = 1

    [[menu.nav]]
        name = "Posts"
        url = "/posts"
        weight = 2

    [[menu.nav]]
        name = "Now"
        url = "/now"
        weight = 3

    [[menu.nav]]
        name = "Tags"
        url = "/tags"
        weight = 4

    [[menu.nav]]
        name = "Contact"
        url = "/contact"
        weight = 5
